# Generated by Django 5.2.9 on 2026-01-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='threshold',
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
