# Generated by Django 5.2.9 on 2026-01-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_product_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='threshold',
            field=models.IntegerField(default=5),
        ),
    ]
