# Generated by Django 5.2.9 on 2026-01-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequest',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DELIVERED', 'Delivered'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
